[tool.poetry]
name = "acled"
version = "0.1.2"
description = "A Python library that wraps the ACLED API."
authors = ["Blaze Burgess <blaze.i.burgess@gmail.com>"]
license = "GPL 3"
readme = "README.md"
homepage = "https://github.com/blaze.i.burgess/acled"
repository = "https://github.com/blaze.i.burgess/acled"
packages = [
    { include = "acled" },
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.26.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
